### ISSUE TITLE
Editor makes Vita turn off on boot

### ISSUE THREAD

**Issue by ghost** [devnoname120/vitabright-lut-editor#3]
I'm running a Japanese 3.65 2000 Vita with Enso.
I have the vitabright files in ur0:/tai/ and have vitabright in my config.txt.
I've installed the VPK with multiple sources (releases page here, homebrew appstore) multiple times
I've tried the editor out with different vitabright_lut.txt, and I keep getting the same result (which is getting a black screen that eventually causes the Vita to turn off.
The brightness feature of vitabright works without any issue.
Thank you very much!!

**Comment by devnoname120** [comment]
Vitabright LUT editor only works on the PSV 1000 model.
I've created an issue to add info in the repo: https://github.com/devnoname120/vitabright-lut-editor/issues/4
